ffxiv_recruitment_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('accounts/signup/', views.signup, name='signup'),
    path('my_players/', views.my_player_index, name='my_player_index'),
    path('players/', views.all_player_index, name='all_player_index'),
    path('players/<int:player_id>/', views.player_detail, name='player_detail'),
    path('players/create/', views.PlayerCreate.as_view(), name='player_create'),
    path('player/<int:pk>/update', views.PlayerUpdate.as_view(), name='player_update'),
    path('player/<int:pk>/delete', views.PlayerDelete.as_view(), name='player_delete'),
    path('players/<int:player_id>/add-job/', views.add_job, name='add_job'),
    path('jobs/<int:pk>/update/', views.JobUpdate.as_view(), name='job_update'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from image_cropping import ImageCropField, ImageRatioField

ROLES = (
    ('T', 'Tank'),
    ('H', 'Healer'),
    ('D', 'DPS')
)

SERVERS = (
    ("01", "Adamantoise"),
    ("02", "Aegis"),
    ("03", "Alexander"),
    ("04", "Anima"),
    ("05", "Asura"),
    ("06", "Atomos"),
    ("07", "Bahamut"),
    ("08", "Balmung"),
    ("09", "Behemoth"),
    ("10", "Belias"),
    ("11", "Brynhildr"),
    ("12", "Cactuar"),
    ("13", "Carbuncle"),
    ("14", "Cerberus"),
    ("15", "Chocobo"),
    ("16", "Coeurl"),
    ("17", "Diabolos"),
    ("18", "Durandal"),
    ("19", "Excalibur"),
    ("20", "Exodus"),
    ("21", "Faerie"),
    ("22", "Famfrit"),
    ("23", "Fenrir"),
    ("24", "Garuda"),
    ("25", "Gilgamesh"),
    ("26", "Goblin"),
    ("27", "Gungnir"),
    ("28", "Hades"),
    ("29", "Hyperion"),
    ("30", "Ifrit"),
    ("31", "Ixion"),
    ("32", "Jenova"),
    ("33", "Kujata"),
    ("34", "Lamia"),
    ("35", "Leviathan"),
    ("36", "Lich"),
    ("37", "Louisoix"),
    ("38", "Malboro"),
    ("39", "Mandragora"),
    ("40", "Masamune"),
    ("41", "Mateus"),
    ("42", "Midgardsormr"),
    ("43", "Moogle"),
    ("44", "Odin"),
    ("45", "Omega"),
    ("46", "Pandaemonium"),
    ("47", "Phoenix"),
    ("48", "Ragnarok"),
    ("49", "Ramuh"),
    ("50", "Ridill"),
    ("51", "Sargatanas"),
    ("52", "Shinryu"),
    ("53", "Shiva"),
    ("54", "Siren"),
    ("55", "Tiamat"),
    ("56", "Titan"),
    ("57", "Tonberry"),
    ("58", "Typhon"),
    ("59", "Ultima"),
    ("60", "Ultros"),
    ("61", "Unicorn"),
    ("62", "Valefor"),
    ("63", "Yojimbo"),
    ("64", "Zalera"),
    ("65", "Zeromus"),
    ("66", "Zodiark"),
    ("67", "Spriggan"),
    ("68", "Twintania"),
    ("69", "Bismarck"),
    ("70", "Ravana"),
    ("71", "Sephirot"),
    ("72", "Sophia"),
    ("73", "Zurvan"),
    ("74", "Halicarnassus"),
    ("75", "Maduin"),
    ("76", "Marilith"),
    ("77", "Seraph"),
    ("78", "Alpha"),
    ("79", "Phantom"),
    ("80", "Raiden"),
    ("81", "Sagittarius")
)

JOBS = (
    ('PLD', 'Paladin'),
    ('WAR', 'Warrior'),
    ('DRK', 'Dark Knight'),
    ('GNB', 'Gunbreaker'),
    ('WHM', 'White Mage'),
    ('SCH', 'Scholar'),
    ('AST', 'Astrologian'),
    ('SGE', 'Sage'),
    ('MNK', 'Monk'),
    ('DRG', 'Dragoon'),
    ('NIN', 'Ninja'),
    ('SAM', 'Samurai'),
    ('RPR', 'Reaper'),
    ('VPR', 'Viper'),
    ('BRD', 'Bard'),
    ('MCH', 'Machinist'),
    ('DNC', 'Dancer'),
    ('BLM', 'Black Mage'),
    ('SMN', 'Summoner'),
    ('RDM', 'Red Mage'),
    ('PCT', 'Pictomancer'),
)

class Player(models.Model):
    name = models.CharField(max_length=20)
    player_img = ImageCropField(blank=True, null=True, upload_to='images/')
    cropping = ImageRatioField('player_img', '271x271')
    server = models.CharField(
        max_length=2,
        choices=SERVERS,
        default=SERVERS[0][0]
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.CharField(
        max_length=1,
        choices=ROLES,
        default=ROLES[0][0]
    )
    contact = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.name} is a {self.get_role_display()} on {self.get_server_display()}"
    def get_absolute_url(self):
        return reverse('player_detail', kwargs={'player_id': self.id})

class Job(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    name = models.CharField(
        max_length=3,
        choices=JOBS,
        default=JOBS[0][0]
    )
    description = models.TextField()

    def __str__(self):
        return f'{self.player}\'s {self.name}'
    def get_absolute_url(self):
        return reverse('player_detail', kwargs={'player_id': self.player.id})

main_app/forms.py
from django import forms
from .models import Job

class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['name', 'description']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Player, Job
from .forms import JobForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Create your views here.
class Home(LoginView):
    template_name = 'home.html'

def about(request):
    return render(request, 'about.html')

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

@login_required
def all_player_index(req):
    players = Player.objects.all()
    jobs = Job.objects.filter(player__in=players)
    return render(req, 'players/index.html', {
        'players': players,
        'jobs': jobs
    })

@login_required
def my_player_index(req):
    players = Player.objects.filter(user=req.user)
    jobs = Job.objects.filter(player__in=players)
    return render(req, 'users/index.html', {
        'players': players,
        'jobs': jobs
    })

@login_required
def player_detail(req, player_id):
    player = Player.objects.get(id=player_id)
    jobs = Job.objects.filter(player=player)
    job_form = JobForm()
    return render(req, 'players/detail.html', {
        'player': player,
        'jobs': jobs,
        'job_form' : job_form,
    })

@login_required
def add_job(req, player_id):
    form = JobForm(req.POST)
    if form.is_valid():
        new_job = form.save(commit=False)
        new_job.player_id = player_id
        new_job.save()
    return redirect('player_detail', player_id=player_id)

class JobUpdate(LoginRequiredMixin, UpdateView):
    model = Job
    fields = ['name', 'description']

class PlayerCreate(LoginRequiredMixin, CreateView):
    model = Player
    fields = ['name', 'player_img', 'server', 'role', 'contact']
    success_url = '/my_players/'
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PlayerUpdate(LoginRequiredMixin, UpdateView):
    model = Player
    fields = ['name', 'player_img', 'cropping', 'server','role', 'contact']

class PlayerDelete(LoginRequiredMixin, DeleteView):
    model = Player
    success_url = '/my_players/'

main_app/templates/about.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/about.css' %}" />
{% endblock %} 
{% block content %}
  <body>
    <h1 class="about-header">About</h1>
    <div class="about">
    <p>
      The FFXIV Recruitment Tracker is an app designed for people that want to take
      part in group content but don't know where to look.
      <ul>
        <li><b>Community Focused:</b> Become part of a friendly, active group of adventurers dedicated to exploring Eorzea together.</li>
        <li><b>All Playstyles Welcome:</b> Whether you're a seasoned raider, casual player, or crafting enthusiast, there's a place for you here.</li>
        <li><b>Easy Access:</b> Create a libary of your own players and browse through our community of players to see who you can recruit!</li>
      </ul>
    </p>
  </div>
  </body>
</html>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="static/images" href="{% static 'images/cactuar-icon.png' %}" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <title>FFXIV: Recruitment Tracker</title>
    {% block head %}
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img id="cactuar" src="{% static 'images/ffxiv-logo.png' %}" alt="cactuar icon" />
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'all_player_index' %}">Community Page</a></li>
          <li><a href="{% url 'my_player_index' %}">My Players</a></li>
          <li><a href="{% url 'player_create' %}">New Player</a></li>
          <li>
            <form id="logout-form" method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit">Log out</button>
            </form>
          </li>
          {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Sign In</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
     {% block content %}
     {% endblock %}
     </main>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
{% block content %}


{% if not user.is_authenticated %}
<section class="login-container">
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %} {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}" />
      <button type="submit" class="btn submit">Login</button>
    </form>
</section>
{% endif %}
  
{% endblock %}
  

main_app/templates/main_app/job_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %}
{% block content %}

<div class="page-header">
    <h1>Update Job</h1>
</div>

<form action="" method="post" class="form-container">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/player_confirm_delete.html
{% extends 'base.html' %}  
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/main_app/player_confirm_delete.css' %}">
{% endblock %}
{% block content %}

<div class="content-container">
  <div class="page-header">
    <h1>Delete Player?</h1>
    <h2>Are you sure you want to delete {{ player.name }}?</h2>
    <img src="{% static 'images/moogle-icon.png' %}" alt="a moogle icon" />
  </div>

  <form action="" method="post" class="form">
    {% csrf_token %}
    <a href="{% url 'player_detail' player.id %}" class="btn secondary">Cancel</a>
    <button type="submit" class="btn danger">Yes - Delete!</button>
  </form>
</div>

{% endblock %}

main_app/templates/main_app/player_form.html
{% extends 'base.html' %}
{% load static %}
{% load cropping %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{{ form.media }}
{% endblock %}
{% block content %}

<div class="content-wrap">
    <div class="img-container">
        <img src="{% static 'images/form-background.webp'%}" alt="Form background image">
    </div>

    <div class="form-container">
        <div class="page-header">
            {% if player %}
                <h1>Edit {{ player.name }}</h1>
            {% else %}
                <h1>Add a Player</h1>
            {% endif %}
        </div>

        <form action="" method="post" enctype="multipart/form-data" class="form">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <button type="submit" class="btn submit">Submit!</button>
        </form>
    </div>
</div>

{% endblock %}

main_app/templates/players/detail.html
{% extends 'base.html' %}
{% load static %}
{% load cropping %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/players/details.css' %}">
{% endblock %}
{% block content %}

<section class="player_container">
    <div class="player_details">
        <h1>{{ player.name }}</h1>
        <div class="player_info">
            <h2>{{ player.user }}'s character on {{player.get_server_display}}</h2>
            {% if player.player_img %}
                <img src="{% cropped_thumbnail player "cropping" %}" alt="player uploaded image" />
            {% else %}
                <img id="box-image" src="{% static 'images/chocobo-placeholder.png' %}" alt="a happy chocobo" />
            {% endif %}
        <h3 id="role">Role: {{player.get_role_display}}</h3>
        <h3 id="contact">Contact Information: {{ player.contact }}</h3>
        {% if player.user == request.user %}
            <div class="player-actions">
                <a href="{% url 'player_update' player.id %}" class="btn warn">Edit</a>
                <a href="{% url 'player_delete' player.id %}" class="btn danger">Delete</a>
            </div>
        {% endif %}
    </div>
    </div>
</section>

    <div class="job_container">
        <section class="jobs">
            <div class="subsection-title">
    <h1 id="add_title">Add a Job</h1>
            </div>
    {% if player.user == request.user %}
        <form
        action="{% url 'add_job' player.id %}"
        method="post"
        class="subsection-content"
        autocomplete="off"
        >
            {% csrf_token %}
            {{ job_form.as_p }}
            <button type="submit" class="btn submit">Add Job</button>
        </form>
    {% endif %}

    <div class="job_details">
        <table>
            <thead>
                <tr>
                    <th>Job</th>
                    <th>Description</th>
                </thead>
                <tbody>
            {% if jobs %}
                {% for job in jobs %}
                <tr>
                    <td>{{job.get_name_display}}</td>
                    <td>{{ job.description }}
                        <td>
                    {% if player.user == request.user %}
                        <div class="job-actions">
                            <a href="{% url 'job_update' job.id %}" class="btn job">Edit</a>
                        </div>
                    </td>
                    </td>
                </tr>
                    {% endif %}
                {% endfor %}
            {% else %}
                <p>⚠️ {{player.name}} has no jobs yet!</p>
            {% endif %}
        </ul>
    </table>
</div>
</section>

{% endblock %}

main_app/templates/players/index.html
{% extends 'base.html' %}
{% load static %}
{% load cropping %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/players/index.css' %}">
{% endblock %}
{% block content %}

<section class="index-header">
    <h1>Community Page</h1>
</section>
<section class="player-container">
    {% for player in players %}
        <div class="box">
            <a href="{% url 'player_detail' player.id %}">
                <div class="box-image">
                    {% if player.player_img %}
                        <img src="{% cropped_thumbnail player "cropping" %}" alt="player uploaded image" style="width: 271px; height:271px"/>
                    {% else %}
                        <img id="box-image" src="{% static 'images/chocobo-placeholder.png' %}" alt="a happy chocobo" />
                    {% endif %}
                </div>
                <div class="box-content">
                    <h2 class="box-title">{{ player.name }}</h2>
                    <p>{{ player.user }}'s character on {{player.get_server_display}}</p>
                    <p>Role: {{player.get_role_display}}</p>
                </div>
            </a>
        </div>
    {% endfor %}
</section>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="content-wrap">
  <div class="img-container">
    <img src="{% static 'images/form-background.webp'%}" alt="Form background image">
  </div>
  <div class="form-container">
    <div class="page-header">
      <h1>Sign Up</h1>
      <img src="{% static 'images/moogle-icon.png' %}" alt="moogle icon" />
    </div>
    {% if error_message %}
      <p class="red-text">{{ error_message }}</p>
    {% endif %}
    <form action="" method="post" class="form" autocomplete="off">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <button type="submit" class="btn submit">Submit!</button>
    </form>
  </div>
</div>

{% endblock %}

main_app/templates/users/index.html
{% extends 'base.html' %}
{% load static %}
{% load cropping %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/users/index.css' %}">
{% endblock %}
{% block content %}

<section>
    <h1 class="index-header">My Players</h1>
</section>
<section class="player-container">
    {% for player in players %}
        <div class="box">
            <a href="{% url 'player_detail' player.id %}">
                <div class="box-image">
                    {% if player.player_img %}
                        <img src="{% cropped_thumbnail player "cropping" %}" alt="player uploaded image" style="width: 271px; height:271px"/>
                    {% else %}
                        <img id="box-image" src="{% static 'images/chocobo-placeholder.png' %}" alt="a happy chocobo" />
                    {% endif %}
                </div>
                <div class="box-content">
                    <h2 class="box-title">{{ player.name }}</h2>
                    <p>Server: {{player.get_server_display}}</p>
                    <p>Role: {{player.get_role_display}}</p>
                </div>
            </a>
        </div>
    {% endfor %}
</section>

{% endblock %}